{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openproject.fullname" . }}
  labels: {{- include "openproject.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
     storage: {{ .Values.persistence.size | quote }}
{{- end }}
