apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyoxide.fullname" . }}
  labels:
    {{- include "keyoxide.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "keyoxide.selectorLabels" . | nindent 4 }}
